### ISSUE TITLE
can it be used in bag-level relation extraction?

### ISSUE THREAD

**Issue by ShellingFord221** [zhijing-jin/pytorch_RelationExtraction_AttentionBiLSTM#3]
Hi, it seems that this work is only done on sentence-level relation classification. Can it be used in bag-level relation extraction? Why or why not? Thanks!

**Comment by zhijing-jin** [comment]
Hi, thank you for your question. Sure, it can be used in bag-level relation extraction. For example, if the bag is 
```
Sentence 1. <Entity_0>Barack Obama</Entity_0> was born in the <Entity_1>United States</Entity_1>.
Sentence 2. <Entity_0>Barack Obama</Entity_0> was the 44th president of the <Entity_1>United States</Entity_1>.
```
Then you can treat it as two classification tasks using our model.
|Task|Input|Label|
|--|--|--|
|1|**<Entity_0>Barack Obama</Entity_0>** was born in the **<Entity_1>United States</Entity_1>**. Barack Obama was the 44th president of the United States.|`place_of_birth`|
|2|Barack Obama was born in the United States. **<Entity_0>Barack Obama</Entity_0>** was the 44th president of the **<Entity_1>United States</Entity_1>**.|`is_president_of`|

Admittedly, this is a simple adaptation. There are more complicated models using the intra-bag and inter-bag information such as [(Ye and Ling, 2019 NAACL)](https://arxiv.org/pdf/1904.00143.pdf).
